## Modificaciones a rutina PLU  

* Primeramente, se crea una matriz P igual a la identidad, la cual es modificada con los mismos pivoteos  
que se le aplican a la matriz A durante la implementación del método (explicado a un costado con comentarios) 
* Luego, se resuelve el sistema $LU \cdot \vec{x} = P \cdot \vec{b}$ utilizando la librería linalg de umy para  
invertir, comparando el $\vec{x}$ resultante con el conseguido en el método original 

* Finalmente, se calcula el determinante de A a través del uso de propiedades del determinante mismo, y de la matriz P

In [14]:
import numpy as np

N=3
A = np.empty((N,N))
L = np.empty((N,N))
x = np.empty(N)
y = np.empty(N)
A = np.array([[0., 3., 2.],
              [5., 0., 1.],
              [1., 1., 0.]])
A_orig  = np.array([[0., 3., 2.],
                    [5., 0., 1.],
                    [1., 1., 0.]])
b = np.array([20.,27.,6.])
b_orig = np.array([20.,27.,6.])

# Creo la matriz identidad P a la cual le aplicaré las mismas permutaciones que A
P = np.identity(N)

print('A=')
for row in A:         # print A
    for item in row: 
        print('%.2f      ' % item, end="") 
    print()
    
print('b=')
for item in b:         # print b 
    print('%.2f      ' % item, end="")

print()

print('P=')
for row in P:         # print P
    for item in row: 
        print('%.2f      ' % item, end="")
    print() 

print()


A=
0.00      3.00      2.00      
5.00      0.00      1.00      
1.00      1.00      0.00      
b=
20.00      27.00      6.00      
P=
1.00      0.00      0.00      
0.00      1.00      0.00      
0.00      0.00      1.00      



\begin{equation}
\begin{bmatrix} 
a_{11} & a_{12} & a_{13} & a_{14} \\
a_{21} & a_{22} & a_{23} & a_{24}\\
a_{31} & a_{32} & a_{33} & a_{34}\\
a_{41} & a_{42} & a_{43} & a_{44}\\
\end{bmatrix}
\to
\begin{bmatrix} 
\beta_{11} & a_{12} & a_{13} & a_{14} \\
\alpha_{21} & a_{22} & a_{23} & a_{24}\\
\alpha_{31} & a_{32} & a_{33} & a_{34}\\
\alpha_{41} & a_{42} & a_{43} & a_{44}\\
\end{bmatrix}
\to
\begin{bmatrix} 
\beta_{11} & \beta_{12} & a_{13} & a_{14} \\
\alpha_{21} & \beta_{22} & a_{23} & a_{24}\\
\alpha_{31} & \alpha_{32} & a_{33} & a_{34}\\
\alpha_{41} & \alpha_{42} & a_{43} & a_{44}\\
\end{bmatrix}
\to
\begin{bmatrix} 
\beta_{11} & \beta_{12} & \beta_{13} & a_{14} \\
\alpha_{21} & \beta_{22} & \beta_{23} & a_{24}\\
\alpha_{31} & \alpha_{32} & \beta_{33} & a_{34}\\
\alpha_{41} & \alpha_{42} & \alpha_{43} & a_{44}\\
\end{bmatrix}
\to
\begin{bmatrix} 
\beta_{11} & \beta_{12} & \beta_{13} & \beta_{14} \\
\alpha_{21} & \beta_{22} & \beta_{23} & \beta_{24}\\
\alpha_{31} & \alpha_{32} & \beta_{33} & \beta_{34}\\
\alpha_{41} & \alpha_{42} & \alpha_{43} & \beta_{44}\\
\end{bmatrix}
\end{equation}

Given the elements $a_{i,j}$ of matrix $\mathbf{A}$, for each column $j$ calculate:
1) For $i=1,...,j$:

\begin{equation}
\beta_{ij} = a_{ij} - \sum_{k=1}^{i-1}\alpha_{ik}\beta_{kj}
\end{equation}

\begin{equation}
a_{ij} = \beta_{ij} \,\, (\textrm{i.e., replace}\, a_{ij}\, \textrm{for}\, \beta_{ij})
\end{equation}

2) For $i=j+1,...,N$:

\begin{equation}
\alpha_{ij} = (a_{ij} - \sum_{k=1}^{j-1}\alpha_{ik}\beta_{kj})/\beta_{jj}
\end{equation}

\begin{equation}
a_{ij} = \alpha_{ij} \,\, (\textrm{i.e., replace}\, a_{ij}\, \textrm{for}\, \alpha_{ij})
\end{equation}

In [15]:
for i in range(1,1):
    print(i)

In [16]:
for j in range(1):    # j es el indice de la columna   
    for i in range(1,j+1):
        A[i,j] -= np.dot(A[i,:i],A[:i,j])

print(A[0, 0])

0.0


In [17]:
for j in range(N):    # j es el indice de la columna   
    for i in range(1,j+1):
        A[i,j] -= np.dot(A[i,:i],A[:i,j])

    pivot = A[j,j]

    for i in range(j+1,N): 
        A[i,j] -= np.dot(A[i,:j],A[:j,j])

    pivot_fila = np.argmax(np.abs(A[j:, j])) + j
    if pivot_fila != j:  
        b[[j, pivot_fila]] = b[[pivot_fila, j]]
        A[[j, pivot_fila], :] = A[[pivot_fila, j], :]
        P[[j, pivot_fila], :] = P[[pivot_fila, j], :] # En esta linea se aplican las permutaciones a P

    for i in range(j+1,N): 
        A[i,j] = A[i,j]/A[j,j]

print('A_fin=')
for row in A:         # imprimimos el A final
    for item in row: 
        print('%.2f      ' % item, end="") 
    print()

print('P_fin=')
for row in P:         # imprimimos el P final
    for item in row: 
        print('%.2f      ' % item, end="") 
    print()

A_fin=
5.00      0.00      1.00      
0.00      3.00      2.00      
0.20      0.33      -0.87      
P_fin=
0.00      1.00      0.00      
1.00      0.00      0.00      
0.00      0.00      1.00      


In [18]:
# Here we separate L and U
for i in range(N):
    for j in range(N):
        if i == j:
            L[i,j] = 1
        else:
            if i > j:
                L[i,j] = A[i,j]
                A[i,j] = 0
            else:
                L[i,j] = 0
print('L=')
for row in L:         # a little print function
    for item in row: 
        print('%.2f      ' % item, end="") 
    print()
print('U=')
for row in A:         # a little print function
    for item in row: 
        print('%.2f      ' % item, end="") 
    print()

L=
1.00      0.00      0.00      
0.00      1.00      0.00      
0.20      0.33      1.00      
U=
5.00      0.00      1.00      
0.00      3.00      2.00      
0.00      0.00      -0.87      


Finally we solve for $\vec{y}$ in the following equation:
\begin{equation}
\mathbf{L}\vec{y} = \vec{b'},
\end{equation}
where the "prime" (') means that the elements of $\vec{b}$ have been subject to the same permutations as $\mathbf{A}$ (this only applies if pivoting has been implemented). Then
\begin{equation}
y_i = b_i' - \sum_{k=1}^{i-1} \alpha_{ik}y_k
\end{equation}

In [19]:
for i in range(N):
    y[i] = b[i] - np.dot(L[i,:i],y[:i])
print('y=',y)

y= [27.         20.         -6.06666667]


And then we solve for $\vec{x}$ in the following equation:
\begin{equation}
\mathbf{U}\vec{x} = \vec{y}.
\end{equation}
This means that:
\begin{equation}
x_i = (y_i - \sum_{k=i+1}^{N} \beta_{ik}x_k)/\beta_{ii}.
\end{equation}

In [20]:
for i in range(N-1, -1, -1):
    x[i] = (y[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
print('x=',x)

x= [4. 2. 7.]


In [21]:
j = 1
N = 6
for i in range(j, N):
    print(i)

1
2
3
4
5


In [22]:
a = [1,2,3,4]
print(a[0:])

[1, 2, 3, 4]


* Cálculo de $\vec{x}$ con matriz $P$ de permutaciones y $\vec{b}$ original

In [23]:
from numpy.linalg import inv as inv
from numpy.linalg import det as det

inv_L = inv(L)
U = np.copy(A) # Aquí A ya fue transformado en U en la separación LU del algortimo original
inv_U = inv(U)
pb = np.dot(P, b_orig) # Producto matricial de P x b, con P ya permutado
x_permut = np.dot(inv_U, np.dot(inv_L, pb)) # Producto matricial de (U^-1) x (L^-1) x P x b

print(x_permut)
print(x)
print('Are they the same array?', np.allclose(x_permut, x))

print(x - x_permut) # Por el uso de linalg, los valores difieren minimamente, 
#                     pero son tan pequeños los números que se pueden considerar 
#                     aceptables de todas maneras.



[4. 2. 7.]
[4. 2. 7.]
Are they the same array? True
[-8.8817842e-16  4.4408921e-16  0.0000000e+00]


* Cálculo del $det(A)$ según las propiedades del determinante del enunciado  

    En este caso aplicamos la propiedad del enunciado que dice que $det(A \cdot B) = det(A)det(B)$ a ambos lados de la ecuación  
    $LU = PA$, y despejamos $det(A)$

In [24]:
det_lu = det(L)*det(U)

det_p = det(P)

det_A = det_lu/det_p

print('Determinante de P =', det_p)
# Aquí se es consistente con lo que se ve en el enunciado, pues P en nuestro caso es 
# la identidad 3x3 con la primera y la segunda filas permutadas, por lo que su determinante es -1

print('Determinante de A =', det_A)

print('Determinante de A (NumPy)', det(A_orig)) # Para confirmar que son iguales

Determinante de P = -1.0
Determinante de A = 13.0
Determinante de A (NumPy) 13.0
